/*
 * SobreJFrame.java
 *
 * Created on 13 de Setembro de 2006, 15:30
 */

package investimento;

/**
 *
 * @author  Deus
 */
public class SobreFrame extends javax.swing.JFrame {
    
    /** Creates new form SobreJFrame */
    public SobreFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPaneSobre1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sobre");

        textPaneSobre1.setBackground(new java.awt.Color(183, 207, 219));
        textPaneSobre1.setEditable(false);
        textPaneSobre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textPaneSobre1.setForeground(new java.awt.Color(255, 255, 255));
        textPaneSobre1.setText("\n      Programa Investimentos - Versão 1.0.\n\n\n     Obs: para períodos menores que 1 mês, o sistema calcula a taxa comercial considerando 30 dias no mês.\n\n\t\t\t\n     Sucesso, 8/3/2010");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(textPaneSobre1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 500, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(textPaneSobre1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SobreFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane textPaneSobre1;
    // End of variables declaration//GEN-END:variables
    
}
